<a href="https://colab.research.google.com/github/HaSeoHyun/DataScience_Python_Practice/blob/main/API_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
d = {"name":"hongongData", "me":"하서현"}
print(d['name'])
import json
#json.dupmps: 파이썬 객체를 JSON 형식의 텍스트로 
d_str = json.dumps(d,ensure_ascii = False) #ensure_ascii: 한글 출력
print(d_str)
print(type(d_str))  #데이터 타입 확인

hongongData
{"name": "hongongData", "me": "하서현"}
<class 'str'>

In [9]:
d2 = json.loads(d_str)  #json.loads()함수: JSON 문자열을 파이썬 객체로 변환 
print(d2['name'])
print(type(d2))

hongongData
<class 'dict'>

In [10]:
d3 = json.loads('{"name":"hong", "author":["박해선","세종대왕"],"year":2022}')
print(d3['author'])
print(d3['author'][1])

['박해선', '세종대왕']
세종대왕

In [11]:
d4_str = '''[  
  {"name":"hong","author":"박해선","year":2022},
  {"name":"data","author":"김민석", "year":2021}
]'''
#따옴표 3개가 중간에: 문자열 줄바꿈이라는 의미. 처음에: 주석
d4 = json.loads(d4_str)
print(d4[0]['name'])

hong

여기부터는 JSON문자열을 데이터프레임으로 변환,

read_json()함수 사용

In [12]:
import pandas as pd
pd.read_json(d4_str)

   name author  year
0  hong    박해선  2022
1  data    김민석  2021

In [ ]:
pd.DataFrame(d4)  #이거는 파이썬 객체에서 만든 데이터프레임

   name author  year
0  hong    박해선  2022
1  data    김민석  2021

In [ ]:
x_str = '''
<book>  
  <name>혼자 공부하는 데이터 분석</name>   
  <author>박해선</author>
  <year>2022</year> 
</book>
'''

'''(주석)
<book>  #루트, 부모   
  <name>혼자 공부하는 데이터 분석</name>   #<name>: 시작 태그, </name>: 종료태그 
  <author>박해선</author>
  <year>2022</year>  # name, author, year: 자식 
</book>  #종료 태그 
'''

import xml.etree.ElementTree as et
book = et.fromstring(x_str)
print(type(book))
print(book.tag)

<class 'xml.etree.ElementTree.Element'>
book

In [ ]:
book_childs = list(book)  #자식 엘리먼트 확인 
print(book_childs)  #자식 엘리먼트 : name, author, year 
name = book.findtext('name')  #findtext()함수로 객체 찾기 
author = book.findtext('author')
year = book.findtext('year')
print(name)
print(author)
print(year)

[<Element 'name' at 0x7f87a4c1eb80>, <Element 'author' at 0x7f87a4c1eea0>, <Element 'year' at 0x7f87a4c1eef0>]
혼자 공부하는 데이터 분석
박해선
2022

조금 더 복잡한 XML 문서

In [ ]:
x2_str = '''
<books>
  <book>
    <name>혼자 공부하는 데이터 분석</name>
    <author>박해선</author>
    <year>2022</year>
  </book>
  <book>
    <name>혼자 공부하는 머신러닝</name>
    <author>김민석</author>
    <year>2020</year>
  </book>
</books>
'''
books = et.fromstring(x2_str)
for book in books.findall('book'):   #여러개 출력 
  name= book.findtext('name')
  author = book.findtext('author')
  year = book.findtext('year')
  print(name)
  print(author)
  print(year)
  print()

pd.read_xml(x2_str)

혼자 공부하는 데이터 분석
박해선
2022

혼자 공부하는 머신러닝
김민석
2020

             name author  year
0  혼자 공부하는 데이터 분석    박해선  2022
1    혼자 공부하는 머신러닝    김민석  2020

In [ ]:
# http://data4library.kr/api/loanItemSrch?format=json&startDt=2021-04-01&endDt=2021-04-30&age=20&authKey=56477804e4a1b1d7aed549ec135ccac0b9a372a3c6ea23fc6fbf7b5a3f833ed2

In [15]:
import requests  #웹 서버로부터 받은 JSON문자열을 파이썬 객체로 변환하여 반환 
url = "http://data4library.kr/api/loanItemSrch?format=json&startDt=2021-04-01&endDt=2021-04-30&age=20&authKey=56477804e4a1b1d7aed549ec135ccac0b9a372a3c6ea23fc6fbf7b5a3f833ed2"
r = requests.get(url)
data = r.json()

#print(data)
books = []  #books변수에 도서 정보가 담긴 딕셔너리 리스트 만들기 
for d in data['response']['docs']:
  books.append(d['doc'])

In [18]:
books_df = pd.DataFrame(books)
books_df

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL
0,1,1,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,468,https://image.aladin.co.kr/product/19359/16/co...
1,2,2,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,396,https://image.aladin.co.kr/product/24512/70/co...
2,3,3,지구에서 한아뿐 :정세랑 장편소설,지은이: 정세랑,난다,2019,9791188862290,03810,,813.7,문학 > 한국문학 > 소설,387,https://image.aladin.co.kr/product/19804/82/co...
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,374,https://image.aladin.co.kr/product/24131/37/co...
4,5,5,아몬드손원평 장편소설,손원평,창비,2017,9788936434267,03810,,813.7,문학 > 한국문학 > 소설,367,http://image.aladin.co.kr/product/16839/4/cove...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,193,오베라는 남자 :프레드릭 배크만 장편소설,지은이: 프레드릭 배크만 ;옮긴이: 최민우,다산북스,2015,9791130605210,03850,,859.7,문학 > 독일문학 > 기타 게르만 문학,79,https://bookthumb-phinf.pstatic.net/cover/090/...
196,197,193,외국어 학습·교수의 원리,지은이: H. Douglas Brown ;이성희,피어슨 에듀케이션 코리아,2015,9791130629636,13740,,707,"언어 > 언어 > 지도법, 연구법 및 교육, 교육재료",79,https://image.aladin.co.kr/product/24054/10/co...
197,198,193,"안녕, 소중한 사람 :정한경 에세이",지은이: 정한경,북로망스,2020,9791197037122,03810,,818,문학 > 한국문학 > 르포르타주 및 기타,79,https://image.aladin.co.kr/product/25152/41/co...
198,199,199,열두 발자국,지은이: 정재승,어크로스,2018,9791160560510,03400,,404,"자연과학 > 자연과학 > 강연집, 수필집, 연설문집",78,https://image.aladin.co.kr/product/15072/28/co...
199,200,200,나의 월급 독립 프로젝트 :3년 만에 30억 벌고 퇴사한 슈퍼개미의 실전 주식투자 ...,유목민 지음,웅진씽크빅,2019,9788901230801,03320,,327.856,사회과학 > 경제학 > 금융,77,https://image.aladin.co.kr/product/18899/99/co...

In [19]:
books_df.to_json('20s_best_book.json')  #만든 목록을 json파일에 저장

In [14]:
import requests  #웹 서버로부터 받은 JSON문자열을 파이썬 객체로 변환하여 반환 
url = "http://data4library.kr/api/loanItemSrch?format=json&startDt=2022-04-01&endDt=2022-04-30&age=20&authKey=56477804e4a1b1d7aed549ec135ccac0b9a372a3c6ea23fc6fbf7b5a3f833ed2"
r = requests.get(url)
data = r.json()   #json()함수: json 문자열을 파이썬 객체로 변환하여 반환한다. 
#print(data)

books = []  #books변수에 도서 정보가 담긴 딕셔너리 리스트 만들기 
for d in data['response']['docs']:
  books.append(d['doc'])
books_df = pd.DataFrame(books)
books_df
#url을 손보면 날짜나 찾는 기준 등을 변경하여 사용할 수 있다.

,no,ranking,bookname,authors,publisher,publication_year,isbn13,addition_symbol,vol,class_no,class_nm,loan_count,bookImageURL
0,1,1,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165341909,03810,,813.7,문학 > 한국문학 > 소설,534,https://image.aladin.co.kr/product/24512/70/co...
1,2,2,우리가 빛의 속도로 갈 수 없다면 :김초엽 소설,지은이: 김초엽,허블,2019,9791190090018,03810,,813.7,문학 > 한국문학 > 소설,517,https://image.aladin.co.kr/product/19359/16/co...
2,3,3,지구 끝의 온실 :김초엽 장편소설,지은이: 김초엽,Giant Books(자이언트북스),2021,9791191824001,03810,,813.7,문학 > 한국문학 > 소설,514,https://image.aladin.co.kr/product/27692/63/co...
3,4,4,"시선으로부터, :정세랑 장편소설",지은이: 정세랑,문학동네,2020,9788954672214,03810,,813.7,문학 > 한국문학 > 소설,440,https://image.aladin.co.kr/product/24131/37/co...
4,5,5,달러구트 꿈 백화점.이미예 장편소설,지은이: 이미예,팩토리나인,2020,9791165343729,03810,2,813.7,문학 > 한국문학 > 소설,416,https://image.aladin.co.kr/product/27587/47/co...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,191,허상의 어릿광대,"히가시노 게이고 (지은이), 김난주 (옮긴이)",재인,2021,9788990982940,,,,> >,86,https://image.aladin.co.kr/product/28511/60/co...
196,197,191,더 해빙 =부와 행운을 끌어당기는 힘 /The having,"이서윤,홍주연 지음",수오서재,2020,9791190382175,03320,,325.2113,사회과학 > 경제학 > 경영관리,86,https://image.aladin.co.kr/product/23400/44/co...
197,198,191,공부의 본질 :절대 공부를 포기하고 싶지 않은 사람들을 위한 9가지 기술,이윤규 지음,빅피시,2021,9791191825176,03190,,373.4,"사회과학 > 교육학 > 학습지도, 교육방법",86,https://image.aladin.co.kr/product/28121/45/co...
198,199,199,파과 :구병모 장편소설,지은이: 구병모,자음과모음,2013,9788957077740,03810,,813.7,문학 > 한국문학 > 소설,85,https://bookthumb-phinf.pstatic.net/cover/072/...
199,200,199,한 스푼의 시간 :구병모 장편소설,지은이: 구병모,위즈덤하우스,2016,9788959130580,03810,,813.7,문학 > 한국문학 > 소설,85,http://image.aladin.co.kr/product/9131/24/cove...